filebeat.inputs:
  - type: container
    paths:
      - '/var/lib/docker/containers/*/*.log'

processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"

  - decode_json_fields:
      fields: ["message"]
      target: "json"
      overwrite_keys: true

output.logstash:
  hosts: ["logs.placeholderdomain.com:5044"]
  ssl.enabled: true
#  ssl.certificate_authorities: ["/usr/share/filebeat/certs/ca.crt"]
#  ssl.certificate: "/usr/share/filebeat/certs/client.crt"
#  ssl.key: "/usr/share/filebeat/certs/client.key"

logging.json: true
logging.metrics.enabled: false
